<footer>
	<p>
	<hr width=50% height="1">
	<i class="fa fa-envelope" style="color: white; font-size: 0.9em; margin-right: 5pt;"></i>
	<a href="mailto:xsun1@hmc.psu.edu" class="footerlink">Email us&nbsp;&nbsp;</a>
	<i class="fa fa-download"  style="color: white; font-size: 0.9em; margin-right: 5pt;"></i>
	<a href="https://github.com/psu-libraries/dashboard" class="footerlink">Download the code</a>
	<p>
</footer>
